name: CI

on: push

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        target:
          [
            x86_64-unknown-linux-gnu,
            aarch64-unknown-linux-gnu,
            x86_64-pc-windows-msvc,
            x86_64-apple-darwin,
            aarch64-apple-darwin,
          ]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: denoland/setup-deno@v1

      - uses: actions/cache@v4
        with:
          path: ~/.cache/deno/deps
          key: ${{ runner.os }}-${{ hashFiles('deno.lock') }}

      - run: BUILD_ARGS="--target ${{ matrix.target }}" deno task build

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: mtkruto-server*
